# Backup the entire network infrastructure
---
- name: Backup all devices
  gather_facts: false
  connection: local
  hosts: all

  collections:
    - lvrfrc87.git_acp
    - gmoisio.ale.ale_aos_command

  tasks:

    # Backup configuration through REST API
    - name: IMPORT >> backups configuration
      include_tasks: backup-aos8.yml
      when: device_os == 'aos8'

    # Write backup file to local directory
    - name: IMPORT >> backups configuration
      import_tasks: backup-to-local.yml
      when: backup_local

